name: my first pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Build image
      run: docker build -t reg2022/ciportfolio .
    - name:

 #       - name: uptime
  #        run: uptime
   #     - name: check no of processors
    #      run: nproc
  #test:
   # runs-on: ubuntu-latest
    #steps:
     #   - name: hello
      #    run: echo "Hello!"