name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for requesting the OIDC JWT token
  contents: read  # Required for checkout

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # -------------------------------------------------------------
      # 2. TRIVY VULNERABILITY SCAN
      # -------------------------------------------------------------
  scan-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
        - name: configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ vars.AWS_REGION }}

        - name: Login to ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: scan image with trivy
          uses: aquasecurity/trivy-action@master

          with:
            image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY}}
            format: table
            exit-code: '0'
            severity: CRITICAL,HIGH

  deploy-ecs:
    needs: scan-image
    runs-on: ubuntu-lates
    steps:

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to ECS
        run:
          aws ecs update-service\
          --cluster ${{ secrets.ECS_CLUSTER }}
          --service ${{ secrets.ECS_SERVICE }}
          --force-new-deployment